name: 'OpenTelemetry for GitHub Repository Events'
description: 'Collect VCS and repository-level metrics from GitHub events'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  self_monitoring:
    description: 'Submit self-monitoring metrics to the OpenTelemetry project'
    default: auto
  self_monitoring_anonymize:
    description: 'Anonymize self-monitoring metrics'
    default: auto
  debug:
    description: 'Enable debug logging'
    default: ${{ runner.debug }}
runs:
  using: composite
  steps:
    - name: 'Instrument Repository Events'
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_SELF_MONITORING: ${{ inputs.self_monitoring }}
        INPUT_SELF_MONITORING_ANONYMIZE: ${{ inputs.self_monitoring_anonymize }}
        INPUT_DEBUG: ${{ inputs.debug }}
      run: bash main.sh
