#!/bin/sh -e
rm -rf /opt/opentelemetry_bash 1> /dev/null 2> /dev/null || true # clean the old install directory
if [ "$1" = 0 ] || [ "$1" = 1 ] || [ "$1" = 2 ]; then set -- configure; fi
if [ "$1" = 'abort-configure' ] || [ "$1" = 'abort-upgrade' ] || [ "$1" = 'abort-remove' ] || [ "$1" = 'abort-deconfigure' ]; then
  true
elif [ "$1" = 'configure' ] || [ "$1" = 'triggered' ] || [ "$1" = 'reconfigure' ]; then
  export HOME="$(eval "echo ~$(whoami)")"
  if ! [ -d /opt/opentelemetry_shell/sdk/venv ] || [ "${OTEL_SHELL_CONFIG_INSTALL_ASSUME:-FALSE}" = FALSE ]; then
    python3 -m venv /opt/opentelemetry_shell/sdk/venv
    . /opt/opentelemetry_shell/sdk/venv/bin/activate
    pip3 install -r /opt/opentelemetry_shell/sdk/requirements.txt
    pip3 check
    deactivate # SKIP_DEPENDENCY_CHECK
  fi
else
  exit 1
fi
