name: 'OpenTelemetry Jobs'
description: 'Observe Github Jobs with OpenTelemetry'
runs:
  using: 'node20'
  pre: 'inject_and_init.js'
  main: 'nop.js'
  post: 'shutdown.js'
inputs:
  __job_status:
    description: 'INTERNAL ONLY - DO NOT SET MANUALLY'
    default: '${{ job.status }}'
  __action_path:
    description: 'INTERNAL ONLY - DO NOT SET MANUALLY'
    default: '${{ github.action_path }}'
