name: 'OpenTelemetry Jobs'
description: 'Observe Github Jobs with OpenTelemetry'
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: composite
  steps:
    - run: echo hello world
inputs:
  github_token:
    description: 'A GitHub token for API access (read-only)'
    default: '${{ github.token }}'
  debug:
    description: 'Enable debug logging'
    default: ${{ runner.debug }}
