name: 'OpenTelemetry Jobs'
description: 'Observe Github Jobs with OpenTelemetry'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  github_token:
    description: 'A GitHub token for API access, needs read access to the scopes repo and actions. Do not set manually unless you know exactly what you are doing, the default token should always be enough.'
    default: '${{ github.token }}'
  cache:
    description: 'Whether to use GitHub Actions Cache to cache dependencies'
    default: true
  secrets_to_redact:
    description: 'A JSON object containing all secrets to redact from any attribute.'
    default: '{ "github_token": "${{ github.token }}" }'
  self_monitoring:
    description: 'Whether to send usage statistics (invocation counts, feature usages) to the maintainer to inform roadmap and maintenance efforts. No data of the workflow itself will be collected. Possible values are true, false, and auto (true for repositories on GitHub SaaS, false for private GitHub servers).'
    default: auto
  self_monitoring_anonymize:
    description: 'Whether to strip self monitoring data of any identifiable information. Possible values are true, false, and auto (false for public repository on GitHub SaaS, true for private GitHub servers and private repositories).'
    default: true
  debug:
    description: 'Enable debug logging'
    default: '${{ runner.debug }}'
  __kill_switch:
    description: 'INTERNAL ONLY - DO NOT SET MANUALLY' # 'Set OTEL_GITHUB_KILL_SWITCH variable for the repository or organization to any non-empty value to disable all monitoring in case of an emergency. DO NOT SET MANUALLY.'
    default: '' # '${{ vars.OTEL_GITHUB_KILL_SWITCH }}'
  __job_status:
    description: 'INTERNAL ONLY - DO NOT SET MANUALLY'
    default: '${{ job.status }}'
  __job_matrix:
    description: 'INTERNAL ONLY - DO NOT SET MANUALLY'
    default: '${{ toJSON(matrix) }}'
runs:
  using: 'node24'
  pre: 'inject_and_init.js'
  main: 'nop.js'
  post: 'shutdown.js'
