name: 'OpenTelemetry Workflow'
description: 'Observe Github Workflows with OpenTelemetry'
runs:
  using: 'node20'
  main: 'main.js'
inputs:
  github_token:
    description: 'A GitHub token for API access (read-only)'
    default: '${{ secrets.GITHUB_TOKEN }}'
  cache:
    description: 'Whether to use GitHub Actions Cache to cache dependencies'
    default: false
