name: 'OpenTelemetry Workflow'
description: 'Observe Github Workflows with OpenTelemetry'
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'node20'
  main: 'main.js'
inputs:
  github_token:
    description: 'A GitHub token for API access (read-only)'
    default: '${{ github.token }}'
  cache:
    description: 'Whether to use GitHub Actions Cache to cache dependencies'
    default: true
  workflow_run_id:
    description: 'The workflow run to observe (id)'
    default: ${{ github.event.workflow_run.id }}
  workflow_run_attempt:
    description: 'The workflow run to observe (attempt)'
    default: ${{ github.event.workflow_run.run_attempt }}
