name: Autorerun
on:
  workflow_run:
    workflows: ['Test', 'Publish', 'Refresh Demos', 'Workflow Example']
    types: completed
  schedule:
    - cron: '0 0 * * *'
concurrency:
  group: rerun-${{ github.event.workflow_run.id }}
jobs:
  rerun:
    runs-on: ubuntu-latest
    permissions:
      contents: none
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.23.0
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.ACTIONS_GITHUB_TOKEN }}"]'
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
      - uses: plengauer/autorerun@v0.28.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
