name: Autoapprove

on:
  pull_request:

concurrency:
  group: approve-${{ github.event.pull_request.number }}

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v5.3.2
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_LOGS_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT }}'
      - uses: plengauer/autoapprove@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_to_approve: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
