name: Autorerun

on:
  workflow_run:
    workflows: [ 'Test', 'Publish' ]
    types: completed
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: rerun-${{ github.event.workflow_run.id }}

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/autorerun@v0.14.1
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
