name: Autorerun

on:
  workflow_run:
    workflows: [ 'Test', 'Publish', 'Refresh Demos', 'Workflow Example' ]
    types: completed
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: rerun-${{ github.event.workflow_run.id }}

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/thoth/actions/instrument/job@v5.10.2
        with:
          secrets_to_redact: '${{ toJSON(secrets) }}'
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
      - uses: plengauer/autorerun@v0.21.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
