name: Autorerun

on:
  workflow_run:
    workflows: [ 'Test', 'Publish' ]
    types: completed

concurrency:
  group: rerun-${{ github.event.workflow_run.id }}

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/autorerun@v0.11.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
