name: Autorerun

on:
  workflow_run:
    workflows: [ 'Test', 'Publish', 'Refresh Demos', 'Workflow Example' ]
    types: completed
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: rerun-${{ github.event.workflow_run.id }}

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v5.3.2
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_LOGS_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT }}'
      - uses: plengauer/autorerun@v0.18.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
