name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install devscripts debhelper alien
      - run: sed -i "s/__VERSION__/$(cat ../VERSION)/g" DEBIAN/control
      - run: dpkg-deb --root-owner-group -Zgzip --build . ../package.deb
      - run: |
          alien --to-rpm --scripts --keep-version --generate ../package.deb
          rpm_dir=$(echo */*.spec | rev | cut -d / -f 2- | rev)
          {
            echo -n 'Requires: ' && cat DEBIAN/control | grep Depends | cut -d ' ' -f 2- | tr ',' '\n' | tr -d ' ' | sed 's/|/ or /g' | tr -d '(' | tr -d ')' | sed 's/.*/(&)/g' | grep -v 'python3-venv' | sed 's/xxd/(xxd or vim-common or vim)/g' | tr '\n' ' ' && echo
            echo "AutoReq: no"
            echo "BuildArch: noarch"
            # cat "$rpm_dir"/*.spec
            cat "$rpm_dir"/*.spec | while read -r line; do
              case "$line" in
                '%post'*)
                  cat DEBIAN/triggers | grep -v '^$' | cut -d ' ' -f 2 | rev | cut -d / -f 1 | rev | sort -u | while read -r package; do
                    cat "$rpm_dir"/*.spec | sed -n '/^%post/,/^$/p' | sed 's/^%post/%triggerin -- '"$package"'/g'
                  done
                  ;;
                *) ;;
              esac
              echo "$line"
            done
          } > rpm.spec && rm "$rpm_dir"/*.spec
          rpmbuild -bb --buildroot="$(cat rpm.spec | grep '^Buildroot: ' | cut -d ' ' -f 2)" rpm.spec
          mv ../*.rpm ../package.rpm
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: package.*
