name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install devscripts debhelper alien
      - run: sed -i "s/__VERSION__/$(cat ../VERSION)/g" DEBIAN/control
      - run: dpkg-deb --root-owner-group -Zgzip --build . ../package.deb
      - run: |
          alien --to-rpm --scripts --keep-version --generate ../package.deb
          rpm_dir=$(echo */*.spec | rev | cut -d / -f 2- | rev)
          {
            echo "BuildArch: noarch"
            cat DEBIAN/control | sed 's/Depends/Requires/g' | grep Requires | tr ',' '\n' | sed 's/: /:\n/g' | tr -d ' ' | grep -v '|' | tr '\n' ' ' && echo
            cat "$rpm_dir"/*.spec
          } > rpm.spec && cat < rpm.spec > "$rpm_dir"/*.spec && rm rpm.spec
          rpmbuild -bb --buildroot="$(cat rpm.spec | grep '^Buildroot: ' | cut -d ' ' -f 2)" "$rpm_dir"/*.spec
          mv *.rpm ../package.rpm
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: package.*

  experiment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: sudo apt-get update && sudo apt-get install rpm alien
      - uses: actions/download-artifact@v4
        with:
          name: packages
      - run: rpm -ql ./package.rpm
      - run: rpm -q --scripts ./package.rpm
      - run: rpm -qR ./package.rpm
      - run: rpm -qi ./package.rpm
      - run: rpm2cpio ./package.rpm | cpio -idmv '*.spec'
      - run: ls
      - run: |
          cat *.spec
