name: Build

on:
  workflow_call:

jobs:
  verify-python-dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          min_version_otel="$(curl https://pypi.org/project/opentelemetry-api/ | grep -F -- 'Python :: ' | cut -d ':' -f 3 | tr -d ' ' | grep -F -- 3. | cut -d . -f 2 | sort -n | head -n 1)"
          min_version_shell="$(cat src/DEBIAN/control | grep '^Depends:' | tr ',' '\n' | grep -F -- 'python3 (>=' | cut -d '(' -f 2- | cut -d ')' -f 1 | cut -d ' ' -f 2 | cut -d . -f 2)"
          [ "$min_version_shell" -ge "$min_version_otel" ]

  verify-debian-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get -y install apt-file
      - run: sudo apt-file update
      - run: |
          patternify() { grep -v '^$' | grep -P '^[a-zA-Z-_.]+$' | while read -r pattern; do echo '^'"$pattern"'$'; done }
          dependencies="$(cat src/DEBIAN/control | grep -E '^Depends:|^Suggests:|^Recommends:' | cut -d : -f 2- | tr '|' ',' | tr ',' '\n' | cut -d '(' -f 1 | tr -d ' ' | sed 's/^awk$/gawk/g' | patternify)"
          find src -iname '*.sh' | xargs cat \
            | grep -v 'SKIP_DEPENDENCY_CHECK' | while read -r line; do line="${line%%#*}"; printf '%s\n' "$line"; done \
            | grep -oP '\\[a-zA-Z][a-zA-Z0-9-_.]*' | while read -r command; do command="${command#\\}"; [ "${#command}" -gt 1 ] && printf '%s\n' "$command" || true; done \
            | grep -vE '^_otel|^otel_|^OTEL_' | grep -vE "$(compgen -b | patternify)" | grep -vE "$(compgen -k | patternify)" \
            | grep -vE '^which$' | grep -vE '^rpm$' | sed 's/^awk$/gawk/g' \
            | sort -u | while read -r command; do
              sudo apt-file search "$command" | grep -E "/$command\$" | cut -d : -f 1 | grep -q -- "$dependencies" && echo "$command OK" || echo "$command UNAVAILABLE"
            done | tee /dev/stderr | grep -q 'UNAVAILABLE' && exit 1 || exit 0

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install devscripts debhelper alien
      - run: sed -i "s/__VERSION__/$(cat ../VERSION)/g" DEBIAN/control
      - run: dpkg-deb --root-owner-group -Zgzip --build . ../package.deb
      - run: |
          alien --to-rpm --scripts --keep-version --generate ../package.deb
          rpm_dir=$(echo */*.spec | rev | cut -d / -f 2- | rev)
          {
            dependencies_format_deb_to_rpm() {
              tr '(' ' ' | tr -d ')' | sed 's/=/= /g' | sed 's/|/ or /g' | sed 's/.*/(&)/g'
            }

            dependencies_content_deb_to_rpm() {
              grep -v 'python3-venv' | sed 's/^awk$/gawk | mawk/g' | sed 's/^dpkg$/rpm/g' | sed 's/^xxd$/xxd | vim-common | vim/g'
            }
          
            echo -n 'Requires: ' && cat DEBIAN/control | grep Depends | cut -d ' ' -f 2- | tr ',' '\n' | tr -d ' ' | grep -v '^$' | dependencies_content_deb_to_rpm | dependencies_format_deb_to_rpm | tr '\n' ' ' && echo
            echo "AutoReq: no"
            echo "BuildArch: noarch"
            cat "$rpm_dir"/*.spec # | while read -r line; do
            #  case "$line" in
            #    '%post'*)
            #      cat DEBIAN/triggers | grep -v '^$' | cut -d ' ' -f 2 | rev | cut -d / -f 1 | rev | sort -u | while read -r package; do
            #        cat "$rpm_dir"/*.spec | sed -n '/^%post/,/^$/p' | sed 's/^%post/%triggerin -- '"$package"'/g'
            #        cat "$rpm_dir"/*.spec | sed -n '/^%post/,/^$/p' | sed 's/^%post/%triggerun -- '"$package"'/g'
            #      done
            #      ;;
            #    *) ;;
            #  esac
            #  printf '%s\n' "$line"
            #done
          } > rpm.spec && rm "$rpm_dir"/*.spec
          rpmbuild -bb --buildroot="$(cat rpm.spec | grep '^Buildroot: ' | cut -d ' ' -f 2)" rpm.spec
          mv ../*.rpm ../package.rpm
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: package.*
