name: Bump Patch Version
on:
  push:
    branches:
      - 'release/v*.*'
concurrency:
  group: bump-version-${{ github.ref }}
  cancel-in-progress: false
jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          ref: ${{ github.ref }}
      
      - id: check
        run: |
          if git log -1 --pretty=%B | grep -q "^Bump patch version to"; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi
      
      - if: steps.check.outputs.skip == 'false'
        run: |
          set -e
          
          echo "::group::Bump patch version"
          current_version=$(cat VERSION)
          major=$(echo "$current_version" | cut -d. -f1)
          minor=$(echo "$current_version" | cut -d. -f2)
          patch=$(echo "$current_version" | cut -d. -f3)
          
          new_patch=$((patch + 1))
          new_version="${major}.${minor}.${new_patch}"
          echo "$new_version" > VERSION
          
          git add VERSION
          git commit -m "Bump patch version to $new_version"
          git push origin "${{ github.ref_name }}"
          echo "::endgroup::"
