name: Demo

on:
  workflow_call:
  push:

jobs:
  demo-prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.demos.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd demos && echo */ | tr ' ' '\n' | jq -nR '{"include": [inputs | select(length > 0) | {demo_directory: .}]}' | tr -d '\n' | xargs -0 -I {} echo 'matrix={}' >> "$GITHUB_OUTPUT"
        id: demos

  demo-generate:
    needs: demo-prepare
    runs-on: ubuntu-latest
    strategy: 
      matrix: ${{ fromJSON(needs.demo-prepare.outputs.matrix) }}
    steps:
      - run: wget -O - https://raw.githubusercontent.com/plengauer/opentelemetry-bash/main/INSTALL.sh | sh
      - uses: actions/checkout@v4
      - run: |          
          cd demos/${{ matrix.demo_directory }}
          export OTEL_METRICS_EXPORTER=console
          export OTEL_LOGS_EXPORTER=console
          export OTEL_TRACES_EXPORTER=console
          export OTEL_SHELL_SDK_REDIRECT="$(mktemp)"
          bash -e ./demo.sh || true
          cat "$OTEL_SHELL_SDK_REDIRECT"

          rm README.md || true
          echo '´´´json' >> README.md
          cat "$OTEL_SHELL_SDK_REDIRECT" >> README.md
          cat README.md
      # open PR
      # auto merge
          
          
      
