name: Experiment

on:
  workflow_dispatch:
  push:
      paths:
        - .github/workflows/expriment.yaml

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Install otel-bash
        run: |
          wget -O - https://raw.githubusercontent.com/plengauer/opentelemetry-bash/main/INSTALL.sh | sh

      - name: Create otel-shell script
        run: |
          cat << 'EOF' > otel_test.sh
          #!/bin/bash
          which otel.sh
          echo "Current shell traps:"
          trap
          export OTEL_TRACES_EXPORTER=console
          export OTEL_SERVICE_NAME=shell-demo-otel
          . /usr/bin/otel.sh
          curl -s https://api64.ipify.org
          EOF

      - name: Run the otel script
        run: bash otel_test.sh
