name: Experiment

on:
  push:

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: packages
      - uses: ./actions/instrument/job
        with:
          secrets_to_redact: '${{ toJSON(secrets) }}'
        env:
          OTEL_SHELL_CONFIG_GITHUB_INJECT_ON_MAIN: 'TRUE'
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
      - uses: renovatebot/github-action@v41.0.14
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_DRY_RUN: full
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
