name: Experiment
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/experiment.yml
jobs:
  env:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-26, macos-latest, windows-latest, ubuntu-slim]
    runs-on: ${{ matrix.runner }}
    permissions:
      actions: read
    steps:
      - run: printenv
      - if: ${{ matrix.runner == 'ubuntu-slim' }}
        run: ls -la /.dockerenv || true
      - if: ${{ matrix.runner == 'ubuntu-slim' }}
        run: cat /proc/1/cgroup || true
  experiment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - run: exit 0
